/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.search.backend.elasticsearch.lowlevel.index.mapping.impl;

import java.util.Collections;
import java.util.Map;
import java.util.TreeMap;
import org.hibernate.search.backend.elasticsearch.gson.impl.SerializeExtraProperties;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;

/**
 * An object representing Elasticsearch type mappings.
 * <p>
 * See <a href="https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping">Mapping</a>.
 */
/*
 * CAUTION: JSON serialization is controlled by a specific adapter, which must be
 * updated whenever fields of this class are added, renamed or removed.
 */
public abstract class AbstractTypeMapping {

    private DynamicType dynamic;

    /**
     * Must be null when we don't want to include it in JSON serialization.
     */
    protected Map<String, PropertyMapping> properties;

    @SerializeExtraProperties
    private Map<String, JsonElement> extraAttributes;

    public DynamicType getDynamic() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public void setDynamic(DynamicType dynamic) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public Map<String, PropertyMapping> getProperties() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    private Map<String, PropertyMapping> getInitializedProperties() {
        if (properties == null) {
            properties = new TreeMap<>();
        }
        return properties;
    }

    public void addProperty(String name, PropertyMapping mapping) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public void removeProperty(String name) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public Map<String, JsonElement> getExtraAttributes() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    public void setExtraAttributes(Map<String, JsonElement> extraAttributes) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Merge this mapping with another mapping generated by Hibernate Search:
     *
     * <ol>
     * <li>The value for the {@code dynamic} mapping parameter will be taken from the {@code other} unless {@code this} provides a non-null value.</li>
     * <li>The mapping parameter {@code properties} will be merged, using properties defined in both {@code this} and {@code other}.</li>
     * <li>Mapping parameters other than {@code dynamic} and {@code properties} will be those from {@code this};
     * those from {@code other} will be ignored.</li>
     * <li>If a property is defined on both sides, it will be merged recursively as described above.</li>
     * </ol>
     *
     * @param other The other mapping.
     */
    public void merge(AbstractTypeMapping other) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }
}
